spring.application.name=TaskManager2
server.port=8080

# MySQL Configuration 
spring.datasource.url=jdbc:mysql://localhost:3306/task_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true

# Security Keys 
jwt.key=mySecretKeyForTaskManagerApplicationThatIsVeryLongAndSecure123456789
spring.security.oauth2.client.registration.google.client-id= 
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=email,profile
aes.key=1234567890123456
cors.allowed-origins=http://localhost:3000,http://localhost:5173