spring.application.name=TaskManager2
server.port=8080

# MySQL Configuration 
spring.datasource.url=jdbc:mysql://localhost:3306/task_db?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true

# Security Keys 
jjwt.key=${JWT_SECRET}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
aes.key=${AES_KEY}
cors.allowed-origins=${CORS_ORIGINS}