name: Vite React CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Use Node.js 24
      uses: actions/setup-node@v6
      with:
        node-version: '24.x'
        cache: 'npm'
        cache-dependency-path: './frontend/taskito frontend/package-lock.json'

    - name: Install dependencies
      run: npm install
      working-directory: './frontend/taskito frontend'

    - name: Build
      run: npm run build
      working-directory: './frontend/taskito frontend'

    # - name: Deploy to Netlify
    #   uses: nwtgck/actions-netlify@v3.0
    #   with:
    #     publish-dir: './frontend/taskito frontend/dist'
    #     production-branch: master
    #     production-deploy: true
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #   env:
    #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
